version: '3'
services:
  backend_magang:
    build: ./php
    image: laravel:latest
    container_name: backend_magang
    hostname: "backend_magang"
    volumes:
      - ./src:/var/www/html
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    working_dir: /var/www/html
    depends_on: 
      - db_magang

  db_magang:
    image: mariadb:10.2
    container_name: db_magang
    restart: unless-stopped
    tty: true
    ports:
      - "13306:3306"
    volumes:
      - ./database/data:/var/lib/mysql
      - ./conf.d:/etc/mysql/conf.d:ro
    environment:
      MYSQL_DATABASE: your_database
      MYSQL_USER: droid
      MYSQL_PASSWORD: roid1234
      MYSQL_ROOT_PASSWORD: roid12345
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql

  nginx_magang:
    build: ./nginx
    image: nginx:latest
    container_name: nginx_magang
    hostname: "nginx_magang"
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend_magang
